#!/bin/bash

moonc ./src
./lp-build.sh
source ./lp-config.sh

butler push "$outputDir/$packageName-${version}_win32.zip" guard13007/the-foundation-falls:win32 --userversion ${version}
butler push "$outputDir/$packageName-${version}_osx.zip" guard13007/the-foundation-falls:osx --userversion ${version}
butler push "$outputDir/$packageName-${version}_linux.zip" guard13007/the-foundation-falls:linux --userversion ${version}
